language: objective-c
osx_image: xcode9.3
script:
    - xcodebuild clean test -project TableViewKit.xcodeproj -scheme TableViewKit-iOS -destination "platform=iOS Simulator,name=iPhone 8,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO